### ISSUE TITLE
Supports setting attributes on the environment

### ISSUE THREAD

**Issue by cderv** [quarto-ext/latex-environment#1]
Some LaTeX environment will need to have attributes set, not only a class equivalent. 

See https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html for how it works in R Markdown. 

We could port the idea and do 

````markdown
:::: {.center}

::: {.minipage latex="{.5\linewidth}"}
This paragraph will be centered on the page, and
its width is 50% of the width of its parent element.
:::

::::
```` 

aim is to write 
````latex
\begin{center}
\begin{minipage}{.5\linewidth}
This paragraph will be centered on the page, and
its width is 50\% of the width of its parent element.
\end{minipage}
\end{center}
````

We could me more precise on the attribute name, but `latex` clearly means this is to be used only with LaTeX. We would for sure ignore for HTML this attribute. 

We also did also made soemthing generic where you need to add the brackets as an environement could be (more on that in https://tex.stackexchange.com/a/302040/209358)

````
\begin{foo}[option]{argument}
body
\end{foo}
````

which would be written
````markdown
::: {.foo latex="[option]{argument}"}
body
:::
````

Anyway, happy to port the feature here. Just wanted to discuss with you what you think is the best way to express that on the custom div.

**Comment by cderv** [comment]
One proposal: 

`````
::: {.foo options="option" arguments="argument"}
body
:::
`````
to transform 

````
\begin{foo}[option]{argument}
body
\end{foo}
````

**Comment by kwangkim** [comment]
A command may need options.

For example,  in an exam class,
```{latex}
\begin{parts}
\part[2] Question 1
\part[3] Question 2
\end{parts}
```

One possible suggestion is

```{markdown}
:::{.parts}
[]{.part options="2"} Question 1
[]{.part options="3"} Question 2
:::
```

With
```{lua}
local function writeCommands(spanEl)
  if quarto.doc.isFormat("latex") then
    for k,v in pairs(classCommands) do
      if spanEl.attr.classes:includes(k) then
        local result = spanEl.content
        local beginCommand = pandoc.RawInline('latex', '\\' .. pandoc.utils.stringify(v) .. '{')
        local endCommand = pandoc.RawInline('latex', '}')

        local opts = spanEl.attr.attributes['options']
        if opts then
          beginCommand = pandoc.RawInline('latex', '\\' .. pandoc.utils.stringify(v) .. '[' .. opts .. ']{')
        end

        table.insert(result, 1, beginCommand)
        table.insert(result, endCommand)

        return result
      end
    end
  end
end
```

**Comment by cderv** [comment]
Thanks @kwangkim I have moved this as a new feature request as I believe even if related this is better to track and discuss independently

**Comment by AngelBerihuete** [comment]
Hi @kwangkim ! I'm wondering if you had success on creating a document with `exam` package. I'm struggling with `solution` and `question` environments, but I have lots of errors. 

Can you share an example using the `exam` package?

Thanks.
