### ISSUE TITLE
Prevent quarto filters

### ISSUE THREAD

**Issue by ratnanil** [quarto-ext/latex-environment#13]
This is a superb extension which I use often. Thank you for your great work.

I'm trying to use the extension to highlight *specific* parts in code blocks. My starting point is just to create a code block using the latex `listings` package.

```md
---
title: test
format: 
    pdf:
        keep-tex: true
        include-in-header:
            text: |
                \usepackage{listings}
filters:
   - latex-environment
environments: [lstlisting]
---

:::{.lstlisting}
    Paired t-test

data: blume$a and blume$b
:::
```

The desired latex output:

```tex
\begin{lstlisting}
    Paired t-test

data: blume$a and blume$b
\end{lstlisting}
```

The created output:

```
\begin{lstlisting}

\begin{verbatim}
Paired t-test
\end{verbatim}

data: blume\(a and blume\)b

\end{lstlisting}
```

I'm guessing quarto ran its own filter over the code, turning the indented `Paired t-test` to `verbatim` and turning `blume$a` to `blume\(a`. Is there a way to prevent quarto from doing this?

**Comment by Nenuial** [comment]
You can "protect" parts from the quarto filters by making then raw latex:
````
:::{.lstlisting}
```{=latex}
    Paired t-test

data: blume$a and blume$b
```
:::
````

This should generate the desired output.

**Comment by ratnanil** [comment]
perfect, it works!
