### ISSUE TITLE
Arguments in commands?

### ISSUE THREAD

**Issue by ratnanil** [quarto-ext/latex-environment#15]
It seems that you have enabled arguments of environments, but not for commands? I'm trying to find a way to create this type of latex output:

```
\colorbox{red}{This text is in a red box}
```

![image](https://github.com/quarto-ext/latex-environment/assets/12532091/4aeb41e4-f601-4b26-a090-44b752d7d6ac)

However, the following file creates this output (note the square brackets).

```md
\colorbox[red]{This text is in a red box}
\colorbox[red]{This text is in a red box}    <!-- arguments are ignored -->
```

``` 
---
title: test
format: 
    pdf:
        keep-tex: true
        include-in-header:
            text: |
                \usepackage{xcolor}
filters:
   - latex-environment
commands: 
  - colorbox
---

[This text is in a red box]{.colorbox options="red"}
[This text is in a red box]{.colorbox options="red" arguments="argument"}
```

**Comment by cderv** [comment]
We are creating the command here: 
https://github.com/quarto-ext/latex-environment/blob/ab5a579508dd02f04340175f7c07f05f0612796b/_extensions/latex-environment/latex-environment.lua#L107-L122

And we indeed only support `\cmd[options]{span content}`. 

Does argument for commands works the same ? 

Is that allowed at some point ? 
````latex
\cmd[options]{argument}{content}
````

**Comment by nilstest** [comment]
> Does argument for commands works the same ?
> 
> Is that allowed at some point ?

Who are you asking :wink: ?

**Comment by nilstest** [comment]
> Does argument for commands works the same ?
> 
> Is that allowed at some point ?

Who are you asking 😉 ?

**Comment by ratnanil** [comment]
> Does argument for commands works the same ?
> 
> Is that allowed at some point ?

Who are you asking 😉 ?

**Comment by cderv** [comment]
I was asking you 😄  It seemed you knew about this LaTeX command

We'll say both are supported. It seems 
* `[ ]`  is used for optional arguments
* `{ }` for mandatory arguments

**Comment by Nenuial** [comment]
> We'll say both are supported. It seems
> 
> * `[ ]`  is used for optional arguments
> * `{ }` for mandatory arguments

I can confirm this.

**Comment by cderv** [comment]
Thanks @Nenuial !

**Comment by cderv** [comment]
I believe this should work, and also handle multiple option and command.

**Comment by ratnanil** [comment]
Perfect! This now works (as per your example.qmd)

```
[This text is in a orange background]{.colorbox arguments="BurntOrange"}
```
