### ISSUE TITLE
Add support for custom LaTeX command associated with an environment

### ISSUE THREAD

**Issue by cderv** [quarto-ext/latex-environment#4]
A command may need options.

For example,  in an exam class,
```{latex}
\begin{parts}
\part[2] Question 1
\part[3] Question 2
\end{parts}
```

One possible suggestion is

```{markdown}
:::{.parts}
[]{.part options="2"} Question 1
[]{.part options="3"} Question 2
:::
```

With
```{lua}
local function writeCommands(spanEl)
  if quarto.doc.isFormat("latex") then
    for k,v in pairs(classCommands) do
      if spanEl.attr.classes:includes(k) then
        local result = spanEl.content
        local beginCommand = pandoc.RawInline('latex', '\\' .. pandoc.utils.stringify(v) .. '{')
        local endCommand = pandoc.RawInline('latex', '}')

        local opts = spanEl.attr.attributes['options']
        if opts then
          beginCommand = pandoc.RawInline('latex', '\\' .. pandoc.utils.stringify(v) .. '[' .. opts .. ']{')
        end

        table.insert(result, 1, beginCommand)
        table.insert(result, endCommand)

        return result
      end
    end
  end
end
```

_Originally posted by @kwangkim in https://github.com/quarto-ext/latex-environment/issues/1#issuecomment-1250318205_

**Comment by cderv** [comment]
@kwangkim I think this would be a new issue for the extension so I opened it to discuss and track separately

Currently, this extension is all about environments (ie `\begin`, `\end`). This means the above would be 

````
::: {.parts}
`\part[2]`{=latex} Question 1

`\part[2]`{=latex} Question 2
:::
````

However, I agree that we could support the syntax you are suggesting. We are doing it in already in some of our LaTeX journals
Example on this filter : https://github.com/quarto-journals/plos/blob/main/_extensions/plos/filter.lua

We could indeed generalize this. Thanks for the suggestion !

**Comment by dragonstyle** [comment]
We just added support for this as v1.0.2. Thx for the detailed suggestion - pretty took your suggestion as is!
