### ISSUE TITLE
Quarto latex stop working on Mac OS

### ISSUE THREAD

**Issue by xomaxy** [quarto-ext/latex-environment#5]
Hi!
This quarto extension has stop working for me for some reason. When I try to run the example code I get this error

`Error running filter _extensions/quarto-ext/latex-environment/latex-environment.lua:
...sions/quarto-ext/latex-environment/latex-environment.lua:66: attempt to call a nil value (field 'is_format')
stack traceback:`

I don't know how to code in Lua, but tracing the history of the commits I found that recently the following line has changed

```{Lua}
if quarto.doc.isFormat("latex") then
# to
   if quarto.doc.is_format("latex") then
```
if I remove this change (to the old `isFormat` ) everything works as usual.
I have the latest version of quarto installed, running on vscode with the quarto extension v1.46.0.

**Comment by dragonstyle** [comment]
We've been changing the underlying API for Quarto and this extension is using the new version. Can you try updating to the latest pre-release of Quarto? That should get it working once again...

https://quarto.org/docs/download/prerelease.html

**Comment by xomaxy** [comment]
it works!
