### ISSUE TITLE
Error with empty div

### ISSUE THREAD

**Issue by jalvesaq** [quarto-ext/latex-environment#6]
First, thanks for developing `latex-environment`!

I'm getting an error when the div is empty in the Quarto document, like this:

```markdown
::: {.sumario}
:::
```

and in the LaTeX template:

```latex
\newenvironment{sumario}{
\thispagestyle{empty}
\singlespacing
\listoffigures
\newpage
\listoftables
\newpage
\tableofcontents
}{\pagebreak}
```

The error is:

```
Error running filter quarto-ext/latex-environment/latex-environment.lua:
latex-environment/latex-environment.lua:87: attempt to index a nil value (field 'integer index')
```

**Comment by dragonstyle** [comment]
Thanks for reporting this - it should be resolved as of version `1.1.1`- you can use `quarto update extension quarto-ext/latex-environment` to update to this version...
